# Generated by Django 3.1.dev20200224072629 on 2020-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roominfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Arrivaldate', models.CharField(max_length=200)),
                ('Timeslot', models.CharField(max_length=200)),
                ('Numberofadults', models.CharField(max_length=200)),
                ('Numberofchildren', models.CharField(max_length=200)),
                ('Comments', models.TextField(max_length=200)),
            ],
        ),
    ]
