# Generated by Django 3.1.dev20200224072629 on 2020-03-12 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetailsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomId', models.IntegerField()),
                ('RoomStarttime', models.IntegerField()),
                ('RoomEndtime', models.IntegerField()),
                ('IsRoomAvailable', models.BooleanField()),
                ('RoomUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
