# Generated by Django 3.1.dev20200224072629 on 2020-03-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetailsnew',
            old_name='RoomStarttime',
            new_name='RoomStarttimeUpdate',
        ),
    ]
