# Generated by Django 3.1.dev20200224072629 on 2020-03-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='numberofadults',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='numberofchildren',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
