# Generated by Django 3.1.dev20200224072629 on 2020-03-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='roominfo',
            new_name='roomdetails',
        ),
    ]
