# Generated by Django 3.1.dev20200224072629 on 2020-03-12 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200312_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDetailsNew',
            new_name='RoomDetails',
        ),
        migrations.RenameField(
            model_name='roomdetails',
            old_name='RoomStarttimeUpdate',
            new_name='RoomStarttime',
        ),
    ]
