# Generated by Django 3.1.dev20200224072629 on 2020-03-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200304_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='Endtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='Starttime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='Numberofadults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='Numberofchildren',
            field=models.IntegerField(),
        ),
    ]
