# Generated by Django 3.1.dev20200224072629 on 2020-03-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200302_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='comments',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
